meta_product_name: "It's A Date"
meta_title: "It's A Date - Uncomplicate the Unforgettable"
meta_description: "It's A Date is a date planning app for any budget with a focus on promoting local businesses and events to bring you unique date activities. Let us help you Uncomplicate the Unforgettable"
meta_image: "cupid_2.jpg" # should exist in `app/assets/images/`
twitter_account: "@_itsadate_"   # required for Twitter Cards